[package]
name = "abc191"
version = "0.1.0"
authors = ["佐藤昭文 <akfm.sato@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
